#!/usr/bin/expect --

# Copyright 2020-2021, 2024 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# (MIT License)

# This can be called from within the context of conman to
# establish an ssh connection to a Mountain node console.
# Usage and examples below assume this script's name is
# ssh-console and located on the system under /usr/bin
#
# Usage: ssh-console xname port user keypath [entrycmd]
#  Example: ssh-console x5000c3s6b0n0 2222 admin /path/to/sshkey
#  Example: ssh-console x5000c3s6b0n0 2222 admin /path/to/sshkey "console"
#
# Example /etc/conman.conf entry:
# console name="x5000c3s6b0n0" dev="/usr/bin/ssh-console x5000c3s6b0n0 2222 admin /path/to/key"
# console name="x5000c3s6b0n0" dev="/usr/bin/ssh-console x5000c3s6b0n0 2222 admin /path/to/key console"
#

set env(TERM) xterm
set bmc [lindex $argv 0]
set port [lindex $argv 1]
set usr [lindex $argv 2]
set keypath [lindex $argv 3]
set entrycmd_encoded [lindex $argv 4]
set timeout -1

# Decode base64 encoded entry command
set entrycmd ""
if {$entrycmd_encoded != ""} {
    set entrycmd [exec echo $entrycmd_encoded | base64 -d]
}

# Default port to 22 if not provided
if {$port == 0} {
    set port 22
}

# Build SSH command with optional entry command
set ssh_cmd [list ssh -p $port -o ServerAliveInterval=180 -o ServerAliveCountMax=5 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i $keypath $usr@$bmc]
if {$entrycmd != ""} {
    lappend ssh_cmd $entrycmd
}

set pid [spawn {*}$ssh_cmd]

exit -onexit {
  exec kill $pid
  wait $pid
  exp_exit
}
interact